### ISSUE TITLE
How to filter for abstracts that apply for a talk?

### ISSUE THREAD

**Issue by janscience** [G-Node/GCA-Python#10]
This is in the abstrTypes field in the Jason file. Unfortunately this is a list, and the only field of interest in the list is "short" ("poster" or "talk"). How can gca-filter used for this? Or: could you update gca_filter to do that? So that a call like
```
./gca-filter abstracts.json "abstypes=talk"
```
will check whether at least one  "short" field in the list is set to "talk".

**Comment by gicmo** [comment]
The line you are looking for should be:

`./gca-filter abstracts.json "abstypes.short=talk"`

**Comment by janscience** [comment]
Thanks! I was actually close to this...

So all what is needed is #12 !
